name: file-name-validator
description: Validate that the file name value matches a regex pattern. The regex pattern for this validator is strict. Length of 3-70 characters. Only alphanumeric, dashes, periods, and plus-signs allowed. No spaces or other special characters allowed.
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'blue'

inputs:

  file_name:
    required: true

  required:
    required: false
    default: true

  error_if_not_valid:
    required: false
    default: true

runs:
  using: "composite"

  steps:

    - name: Validate
      uses: ritterim/public-github-actions/actions/regex-validator@v1.17
      with:
        value: ${{ inputs.file_name }}
        regex_pattern: '^[A-Za-z0-9_\.\+-]{3,70}$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}
