name: version-number-major-minor-validator
description: Validate that the string looks like a "major.minor" version number.
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'blue'

inputs:

  version:
    required: true

  required:
    required: false
    default: true

  error_if_not_valid:
    required: false
    default: true

runs:
  using: "composite"

  steps:

    - name: Validate
      uses: ritterim/public-github-actions/actions/regex-validator@v1.17
      with:
        value: ${{ inputs.version }}
        regex_pattern: '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)?$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}
