name: persist-workspace
description: 'A action to persist your workspace across different jobs'
author: bissolli
branding:
  icon: 'box'  
  color: 'green'

inputs:

  action:
    default: persist
    required: false
    type: choice
    options:
      - retrieve
      - persist

  artifact_name:
    default: 
    required: false

  artifact_name_suffix:
    description: By default, each persisted workspace artifact gets a random suffix appended to the base name.  This input can be used to provide a more meaningful name suffix.
    default: 
    required: false

  retention_days:
    type: number
    default: 3
    required: false
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.

      Default 3 days.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.

outputs:

  artifact_name: 
    description: Name of the artifact which contains the persisted workspace directory.
    value: ${{ steps.set-outputs.outputs.artifact_name }}

env:
  ARTIFACTNAME: 
  TGZFILENAME: workspace.tar.gz

runs:
  using: "composite"
  steps:

    - name: Validate inputs.artifact_name
      uses: ritterim/public-github-actions/actions/file-name-validator@v1.17
      with:
        file_name: ${{ inputs.artifact_name }}
        required: false

    - name: Validate inputs.artifact_name_suffix
      uses: ritterim/public-github-actions/actions/regex-validator@v1.17
      with:
        regex_pattern: '^[a-zA-Z0-9]{2,40}$'
        required: false
        value: ${{ inputs.artifact_name_suffix }}

    - name: Calculate ARTIFACTNAME
      shell: bash
      env:
        INPUTARTIFACTNAME: ${{ inputs.artifact_name }}
        INPUTARTIFACTSUFFIX: ${{ inputs.artifact_name_suffix }}
      run: |
        GITHUBRUNID=${{ github.run_id }}
        RANDOMSUFFIX=$(dd if=/dev/urandom bs=12 count=1 status=none | base64 | tr -dc A-Za-z0-9)
        ARTIFACTSUFFIX=${INPUTARTIFACTSUFFIX:-$RANDOMSUFFIX}
        ARTIFACTNAME=${INPUTARTIFACTNAME:-persisted-workspace-$ARTIFACTSUFFIX-$GITHUBRUNID}
        echo "ARTIFACTNAME=${ARTIFACTNAME}"
        echo "ARTIFACTNAME=${ARTIFACTNAME}" >> $GITHUB_ENV

    - name: Validate inputs.artifact_name
      shell: bash
      run: |
        echo "${ARTIFACTNAME}" | grep -E '^[A-Za-z0-9_\.-]{10,60}'

    - name: Set TGZFILENAME from ARTIFACTNAME
      shell: bash
      run: |
        echo TGZFILENAME="${ARTIFACTNAME}.tgz"
        echo TGZFILENAME="${ARTIFACTNAME}.tgz" >> $GITHUB_ENV

    - name: Create artifact folder
      if: ${{ inputs.action == 'persist' }}
      shell: bash
      run: mkdir tmp-persisted-workspace

    - name: Create the workspace artifact
      if: ${{ inputs.action == 'persist' }}
      shell: bash
      run: |
        tar -czf "tmp-persisted-workspace/${TGZFILENAME}" \
          --exclude=.git \
          --exclude=tmp-persisted-workspace \
          .
        ls -l tmp-persisted-workspace/

    - name: Upload the workspace artifact
      if: ${{ inputs.action == 'persist' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACTNAME }}
        path: tmp-persisted-workspace/${{ env.TGZFILENAME }}
        retention-days: ${{ inputs.retention_days }}
        if-no-files-found: error

    - name: Set output variables
      id: set-outputs
      shell: bash
      run: |
        echo "artifact_name=${ARTIFACTNAME}"
        echo "artifact_name=${ARTIFACTNAME}" >> $GITHUB_OUTPUT

    - name: Retrieve workspace
      if: ${{ inputs.action == 'retrieve' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACTNAME }}

    - name: Extract workspace
      if: ${{ inputs.action == 'retrieve' }}
      shell: bash
      run: tar -xzf "${TGZFILENAME}"
