name: MyGet Publish (NPM)

# Publish the NPM package to the MyGet NPM registry.  
# The artifact file is pulled from the artifacts on the workflow run.

permissions:
  contents: read
  id-token: write
  packages: read

on:

  workflow_call:

    inputs:

      artifact_name:
        description: The GitHub artifact name which contains the package file.  The assumption is that the file is ready for publishing.
        required: true
        type: string

      artifact_file_path:
        description: The filename within the run artifact to be published.
        required: true
        type: string

    secrets:

      myget_api_key:
        description: The secret API key needed in order to access the MyGet API.  These are formatted as GUIDs.
        required: true

jobs:

  publish:
    name: MyGet Publish (NPM)
    runs-on: ubuntu-latest
    env:
      ARTIFACTNAME: ${{ inputs.artifact_name }}
      ARTIFACTFILEPATH: ${{ inputs.artifact_file_path }}

    steps:

      - name: Validate inputs.artifact_name
        uses: ritterim/public-github-actions/actions/file-name-validator@v1.17
        with:
          file_name: ${{ env.ARTIFACTNAME }}

      - name: Validate inputs.artifact_file_path
        uses: ritterim/public-github-actions/actions/file-name-validator@v1.17
        with:
          file_name: ${{ env.ARTIFACTFILEPATH }} 

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: npm-config-myget-packages-repository
        uses: ritterim/public-github-actions/actions/npm-config-myget-packages-repository@v1.16.0
        with:
          myget_api_key: ${{ secrets.myget_api_key }}

      - run: ls -la

      - name: Publish NPM Package File to MyGet
        run: npm publish "${ARTIFACTFILEPATH}"
