name: Test (NPM)

# Execute '`npm run test`' against the package.json file.  There is support 
# for package.json files that are named otherwise or do not exist at the 
# root of the repository.  This workflow *only* runs the build script.
# 
# Note: This restores the workspace created in the npm-build.yml job 
# before executing the test script.

permissions:
  contents: read
  packages: read

on:

  workflow_call:

    inputs:

      persisted_workspace_artifact_name:
        description: Name of the artifact which contains the persisted workspace directory.
        required: false
        type: string
        default:

      project_directory:
        description: Location of the package.json file for the NPM package.
        required: false
        type: string
        default: ./

      run_tests:
        required: false
        type: boolean
        default: true

jobs:

  test:
    name: Test (NPM)
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ${{ inputs.project_directory }}

    env:
      PROJECTDIRECTORY: ${{ inputs.project_directory }}

    steps:

      - name: Validate inputs.project_directory
        uses: ritterim/public-github-actions/actions/path-name-validator@v1.17
        with:
          path_name: ${{ env.PROJECTDIRECTORY }}

      - name: Bypass Tests
        if: inputs.run_tests != true
        working-directory: ./
        run: echo "The 'inputs.run_tests' value is FALSE, skipping tests!"

      - name: Restore Workspace
        uses: ritterim/public-github-actions/forks/persist-workspace@v1.17
        if: inputs.run_tests == true
        with:
          action: retrieve
          artifact_name: ${{ inputs.persisted_workspace_artifact_name }}

      - name: npm run test
        if: inputs.run_tests == true
        run: npm run test
